

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install poetry poetry-plugin-export
      - poetry config virtualenvs.create false
    post_install:
      # Installs the CPU build of torch, see the script
      - bash docs/install_rtd_requirements.sh


# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
